---
- name: install packages
  hosts: all
  become: True
  gather_facts: False

  vars:
    packages:
      - vim
      - tmux
      - nmap-ncat

  tasks:
    - name: install packages
      dnf:
        name: "{{ packages }}"
        state: present

